### ISSUE TITLE
Can i change the text style, like font?

### ISSUE THREAD

**Issue by Yansoltion** [active-programming/DXF-Creator-for-PHP#10]

**Comment by adamasantares** [comment]
@Yansoltion well, no. But there is a code 7 in documentation for text style, but I haven't test it at all...

![image](https://github.com/KOYU-Tech/DXF-Creator-for-PHP/assets/5537618/ba5f95ab-21b0-480c-8814-84a57ff338e6)

I can try on this weekend maybe

**Comment by adamasantares** [comment]
I've merged from one of fork, should work now. See demo1.php
