### ISSUE TITLE
Can i add image to the dxf file?

### ISSUE THREAD

**Issue by Yansoltion** [active-programming/DXF-Creator-for-PHP#11]

**Comment by mariofevre** [comment]
you can use this fork for that.
https://github.com/mariofevre/DXF-Creator-for-PHP

**Comment by Yansoltion** [comment]
its stay not working, i have this error whene i open dxf file :
**Group 91 (db instance count) expected on line 1086.
Group 91 (db instance count) expected on line 1086.
Invalid or incomplete DXF input -- drawing discarded.**

**Comment by mariofevre** [comment]
too bad, want to share de dxf output or de code used t generate it?

**Comment by adamasantares** [comment]
> you can use this fork for that. https://github.com/mariofevre/DXF-Creator-for-PHP

@mariofevre salut. Could you make a pull request from your fork? As I can see you made some updates. Also I can add you to my repository as a contributor/

**Comment by adamasantares** [comment]
> Can i add image to the dxf file?

I'm sorry, but I didn't implement this ability...

**Comment by mariofevre** [comment]
Done.... i think.. I'm not acquainted with github

**Comment by adamasantares** [comment]
Merged to master, will test and publish new version. Thank you @mariofevre !
