### ISSUE TITLE
Hi, fork available

### ISSUE THREAD

**Issue by mariofevre** [active-programming/DXF-Creator-for-PHP#7]
Hi.
Thanks for this piece of code, it was great to find it.
For my own purpouses I had to add some lines in order to insert images y dxf files.
I've tried to follow your code structre, but as I'm not a procoder, I'm sure there are some sloppy lines.
[(https://github.com/mariofevre/DXF-Creator-for-PHP/tree/master)]
Anyway, de addImage function works fine, so if you want to use it great.
Oh, as I know not much about coding, I'm am not sure if this is the right channel to leave this mesagge, if it's not, scuse me.
Reggards.
Mario Fevre

**Comment by adamasantares** [comment]
Hey, unfortunately I do not have to much time to support this lib. So making of forks is correct way :)

But you can do a pull request it you have a time. I'll approve it
