### ISSUE TITLE
Composer package broken?

### ISSUE THREAD

**Issue by tomelgato** [active-programming/DXF-Creator-for-PHP#9]
I encountered something strange. Had v 0.1.15 in a Laravel 6 project, now during update to latest Laravel 8 it was updated to v 0.1.36 (even with 0.1.15 as composer requirement).
This version produces no useable dxf file (after changing the polyLine to polyLine2D calls in my app) and seems rather old/uncomplete. Its still polyLine2D inside and no polyLine. And there is no template.dxf. .
Replacing the creator, color and linetype files + adding the template.dxf from the github 0.1.15 version fixed it (php 8, laravel 8)

P.S. cool lib, thanks for it!

edit: talking about "adamasantares/dxf": "0.1.5" installed via composer

**Comment by adamasantares** [comment]
Hi, I guess you are right, it seems something wrong there, but I don't have a time to fix right now. Hope to fix it during NY holidays...

**Comment by adamasantares** [comment]
new version 0.1.6 published
